### ISSUE TITLE
[Bug] Ollama embedding models stopped working after update to v2.7.0 (build at 2026-03-19T09:38, commit: 15b1466)

### ISSUE THREAD

**Issue by nhshofficial** [1Panel-dev/MaxKB#4916]
### Contact Information

nhshofficial

### MaxKB Version

v2.7.0 (build at 2026-03-19T09:38, commit: 15b1466)

### Problem Description

Embedding models from Ollama / HF stopped working after updating MaxKB to v2.7.0 (build at 2026-03-19T09:38, commit: 15b1466)

### Steps to Reproduce

- update MaxKB to v2.7.0 (build at 2026-03-19T09:38, commit: 15b1466)
- try to vactorize any data.
- error: 'OllamaEmbedding' object has no attribute '_embed'

### Related log output

```shell
OllamaEmbedding' object has no attribute '_embed'
```

**Comment by nhshofficial** [comment]
Fixed at v2.7.1 (build at 2026-03-20T12:03, commit: 5e1a2e5) 
Thanks.
